//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnLesson11Asp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqntaikhoan
    {
        public int PqnId { get; set; }
        public string PqnUseName { get; set; }
        public string PqnPassword { get; set; }
        public string PqnFullName { get; set; }
        public Nullable<int> PqnAge { get; set; }
        public string PqnEmail { get; set; }
        public string PqnPhone { get; set; }
        public Nullable<bool> PqnStatus { get; set; }
    }
}
